### ISSUE TITLE
模型转换报错

### ISSUE THREAD

**Issue by 965525196** [MPolaris/onnx2tflite#62]
Traceback (most recent call last):
  File "\onnx2tflite-main\onnx2tflite-main\onnx_tflite.py", line 2, in <module>
    onnx_converter(
  File "D:\onnx2tflite-main\onnx2tflite-main\converter.py", line 21, in onnx_converter
    keras_model = keras_builder(model_proto, native_groupconv)
  File "D:\onnx2tflite-main\onnx2tflite-main\utils\builder.py", line 82, in keras_builder
    tf_tensor[node_outputs[index]] = tf_operator(tf_tensor, onnx_weights, node_inputs, op_attr, index=index)(_inputs)
  File "D:\Downloads\onnx2tflite-main\onnx2tflite-main\layers\common_layers.py", line 141, in __init__
    pad_shape = pads[i] + pads[i+2]
IndexError: list index out of range

**Comment by zhuweizzz** [comment]
你好，请问你解决了吗，我们也遇到这个问题了

**Comment by 965525196** [comment]
> 你好，请问你解决了吗，我们也遇到这个问题了

我的pt模型里面用了一维卷积，后面换成二维卷积，卷积核n->[1，n]然后解决了

**Comment by wwfu109** [comment]
> > 你好，请问你解决了吗，我们也遇到这个问题了
> 
> 我的pt模型里面用了一维卷积，后面换成二维卷积，卷积核n->[1，n]然后解决了

maxpool1d 也有同样的问题，将一维池化改成二维池化，可以解决此问题，希望可以帮到后面的人。
