### ISSUE TITLE
Error: variable referenced before assignment

### ISSUE THREAD

**Issue by nasircsms** [MPolaris/onnx2tflite#7]
Hi
Trying to convert Yolov7 but getting following error

Traceback (most recent call last):
  File "converter.py", line 64, in <module>
    run()
  File "converter.py", line 60, in run
    image_root=opt.imgroot
  File "converter.py", line 16, in onnx_converter
    keras_model = keras_builder(model_proto)
  File "/yolo/v7/onnx2tflite-main/utils/builder.py", line 84, in keras_builder
    tf_tensor[node_outputs[index]] = tf_operator(tf_tensor, onnx_weights, node_inputs, op_attr, index=index)(_inputs)
  File "/yolo/v7/onnx2tflite-main/layers/common_layers.py", line 290, in __call__
    inputs[i] = tf.cast(inputs, dtype=self.tf_cast_map[self.cast_to])
UnboundLocalError: local variable 'i' referenced before assignment

**Comment by MPolaris** [comment]
oops, it's a bug, you can change 'inputs[i]'(line 288 and 290) in common_layers.py to 'inputs' by yourself, or waiting my updates

**Comment by MPolaris** [comment]
But, Cast op was not used in yolov7, maybe you can set 'need_simplify=True' or 'python converter.py --simplify'
