### ISSUE TITLE
Getting : KeyError: 'LayerNormalization not implemented yet'

### ISSUE THREAD

**Issue by dinusha94** [MPolaris/onnx2tflite#85]
Hi, I am trying to convert an ONNX model to tflite format but I got the following error:

The command I used:
python -m onnx2tflite --weights "/content/bob.paper.tbiom2023_edgeface/edgeface.onnx" --outpath "/content/bob.paper.tbiom2023_edgeface/checkpoints" --formats "tflite"

Error:
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/onnx2tflite/onnx2tflite/__main__.py", line 41, in <module>
    run()
  File "/content/onnx2tflite/onnx2tflite/__main__.py", line 24, in run
    onnx_converter(
  File "/content/onnx2tflite/onnx2tflite/converter.py", line 44, in onnx_converter
    keras_model, input_layout, output_layout = keras_builder(model_proto, native_groupconv)
  File "/content/onnx2tflite/onnx2tflite/components/builder.py", line 43, in keras_builder
    raise KeyError(f"{op_name} not implemented yet")
KeyError: 'LayerNormalization not implemented yet'

Any help on this would be highly appreciated

**Comment by BilalZubairi** [comment]
Did you find any solution for this ?
